# Generated by Django 4.0.5 on 2022-07-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_users_rename_emp_id_employees_na_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('Na_id', models.IntegerField()),
                ('country', models.CharField(blank=True, choices=[('Egypt', 'Egypt'), ('Jaban', 'Jaban')], max_length=50, null=True)),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
