# Generated by Django 4.0.5 on 2022-07-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_user_alter_employee_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, choices=[('Egypt', 'Egypt'), ('Jaban', 'Jaban')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('Egypt', 'Egypt'), ('Jaban', 'Jaban')], max_length=50, null=True),
        ),
    ]
