# Generated by Django 4.0.5 on 2022-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_employee_country_alter_user_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.SlugField(unique=True),
        ),
    ]
