# Generated by Django 3.2.13 on 2022-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_adress_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, choices=[('Jaban', 'Jaban'), ('Egypt', 'Egypt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('Jaban', 'Jaban'), ('Egypt', 'Egypt')], max_length=50, null=True),
        ),
    ]
