# Generated by Django 3.2.13 on 2022-07-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20220705_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.SlugField(unique=True),
        ),
    ]
