# Generated by Django 3.2.13 on 2022-07-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Na_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, choices=[('Egypt', 'Egypt'), ('Jaban', 'Jaban')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Na_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('Egypt', 'Egypt'), ('Jaban', 'Jaban')], max_length=50, null=True),
        ),
    ]
